services:
  - type: web
    name: lab6-frontend-valdez-ryanemmanuel
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://lab6-valdez-ryanemmanuel.onrender.com
